services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: secureiomt-mosquitto
    ports:
      - "1883:1883"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: secureiomt-gateway
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data

  ids:
    build:
      context: .
      dockerfile: ids/Dockerfile
    container_name: secureiomt-ids
    volumes:
      - ./data:/app/data
    depends_on:
      - gateway

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: secureiomt-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - ids

  normal-simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile.normal
    container_name: secureiomt-normal-simulator
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    restart: on-failure

  multi-simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    container_name: secureiomt-multi-simulator
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    restart: on-failure

  attack-data-injection:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    command: ["python", "simulator/attack_data_injection.py"]
    profiles:
      - attacks

  attack-device-spoofing:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    command: ["python", "simulator/attack_device_spoofing.py"]
    profiles:
      - attacks

  attack-dos:
    build:
      context: .
      dockerfile: simulator/Dockerfile.simulator
    environment:
      - BROKER_HOST=mosquitto
    depends_on:
      - mosquitto
    command: ["python", "simulator/attack_dos.py"]
    profiles:
      - attacks